language: rust
dist: xenial
script:
  - 'if [ "$WITH_LOCK" != "true" ]; then cargo update; fi'
  - 'cargo test'
  - 'cargo test --features headers'
  - 'if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then cargo test --features nightly; fi'
# See https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
before_cache:
  - rm -rf /home/travis/.cargo/registry
env: # important!
matrix:
  include:
    - rust: 1.33.0
    - rust: 1.33.0
      os: osx
      env: WITH_LOCK=true
    - rust: stable
      os: osx
    - rust: 1.33.0
      env: WITH_LOCK=true
    - rust: stable
    - rust: nightly
      env: MAY_FAIL=true
  allow_failures:
    - env: MAY_FAIL=true
