name: CI
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '47 15 * * 1,4'

env:
  RUST_BACKTRACE: 1

jobs:

  test:
    name: ${{ matrix.rust }} ${{ matrix.os }} ${{ join(matrix.extras) }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - rust: 1.39.0
            os: ubuntu-20.04
          - rust: 1.39.0
            os: ubuntu-20.04
            extras: [update]
          - rust: 1.39.0
            os: windows-latest
          - rust: 1.39.0
            os: windows-latest
            extras: [update]
          - rust: stable
            os: ubuntu-20.04
            extras: [update]
          - rust: nightly
            os: ubuntu-20.04
            extras: [all]
          - rust: nightly
            os: ubuntu-20.04
            extras: [update, all]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Update Deps
        if: ${{ contains(matrix.extras, 'update') }}
        uses: actions-rs/cargo@v1
        with:
          command: update

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Test (features headers)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features headers

      - name: Test all features/targets
        if: ${{ contains(matrix.extras, 'all') }}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --all-targets
